### ISSUE TITLE
Migrate our News page to sharing/wiki

### ISSUE THREAD

**Issue by cnphil** [sjtug/sjtug.github.io#6]
Per discussions in the mailing list, we've decided to ditch Medium and static pages in favor of a wiki for news event. Please migrate our current "/news" page to the new "sharing/wiki" page.

**Comment by shanzi** [comment]
@cnphil Shut up and give us a Pull Request :hammer:

**Comment by shanzi** [comment]
It seems this issue is no longer valid. Close this? cc @cnphil @htfy96
